version: '2'

services:
  backendpy:
    build: ./backend
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh database:5432 -- /usr/local/bin/python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=database
      - DB_USER=conf
      - DB_NAME=conf
      - DB_PASSWORD=booking
      - DEBUG=True
    image: conf-backpy
    networks:
      - conferences
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
  backendpl:
    build:
      context: ./backend
      dockerfile: Dockerfile.perl
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=conf
      - DB_NAME=conf
      - DB_PASSWORD=booking
    image: conf-backpl
    networks:
      - conferences
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
  database:
    environment:
      - POSTGRES_USER=conf
      - POSTGRES_PASSWORD=booking
    image: postgres:9.6.1
    networks:
      - conferences
    ports:
      - "5432:5432"
  frontend:
    build: ./frontend
    image: conf-front
    networks:
      - conferences
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    image: nginx
    depends_on:
      - frontend
      - backendpy
      - backendpl
    volumes:
      - ./confy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - conferences

networks:
  conferences:
