# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cfp_date', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.CharField(blank=True, max_length=500, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('code_of_conduct', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('accessibility', models.CharField(blank=True, max_length=100, null=True)),
                ('diversity_tickets', models.IntegerField(null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
