# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
