# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20161124_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
